services:
  postgres:
    image: postgres:16
    container_name: sc-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: signalements
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: sc-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sc-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
  mongodata: